services:
  - rabbitmq

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm

install:
  - composer self-update

before_script:
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --no-interaction

script:
  - phpunit --coverage-clover=coverage.clover
  - ./vendor/bin/behat -fprogress --strict

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
