parameters:
  tree_house.queue.driver.amqp.connection.class: AMQPConnection
  tree_house.queue.driver.amqp.channel.class: AMQPChannel
  tree_house.queue.driver.amqp.exchange.class: AMQPExchange
  tree_house.queue.driver.amqp.queue.class: AMQPQueue
  tree_house.queue.driver.amqp.provider.class: TreeHouse\Queue\Message\Provider\AmqpMessageProvider
  tree_house.queue.driver.amqp.publisher.class: TreeHouse\Queue\Message\Publisher\AmqpMessagePublisher
  tree_house.queue.driver.amqp.factory.class: TreeHouse\Queue\Factory\AmqpFactory
  tree_house.queue.serializer.php.class: TreeHouse\Queue\Message\Serializer\PhpSerializer
  tree_house.queue.serializer.json.class: TreeHouse\Queue\Message\Serializer\JsonSerializer
  tree_house.queue.serializer.doctrine.class: TreeHouse\Queue\Message\Serializer\DoctrineSerializer
  tree_house.queue.composer.default.class: TreeHouse\Queue\Message\Composer\DefaultMessageComposer
  tree_house.queue.consumer.class: TreeHouse\Queue\Consumer
  tree_house.queue.event_listener.flush.class: TreeHouse\QueueBundle\EventListener\FlushListener
  tree_house.queue.flusher.doctrine.class: TreeHouse\QueueBundle\Flusher\DoctrineFlusher

services:
  tree_house.queue.driver.amqp.factory:
    class: %tree_house.queue.driver.amqp.factory.class%
  tree_house.queue.serializer.php:
    class: %tree_house.queue.serializer.php.class%
  tree_house.queue.serializer.json:
    class: %tree_house.queue.serializer.json.class%
  tree_house.queue.serializer.doctrine:
    class: %tree_house.queue.serializer.doctrine.class%
    arguments: [@doctrine]
  tree_house.queue.event_listener.queue:
    class: %tree_house.queue.event_listener.flush.class%
    tags:
      - { name: kernel.event_listener, event: queue.flush, method: onFlush }
  tree_house.queue.flusher.doctrine_abstract:
    abstract: true
    public: false
    class: %tree_house.queue.flusher.doctrine.class%
